name: Tag latest

on:
  schedule:
    - cron: "0 0 * * *" # Every night at Midnight.=
  workflow_dispatch:
  
jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: sergeysova/jq-action@v2 # Needed for parsing the JSON of the Superslicer releases.
      - name: checkout repo content
        uses: actions/checkout@v2 # Checkout the repository content to GitHub's runner.
        with:
          ssh-key: "${{ secrets.COMMIT_KEY }}"
      - name: Tag the latest Superslicer if available
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git pull --tags
          chmod +x ./tag_latest_superslicer.sh
          ./tag_latest_superslicer.sh
